server:
  port: 800

spring:
  application:
    name: cloud-consumer-order
  cloud:
  #注册到zookeeper地址
    zookeeper:
#      connect-string: 192.168.111.144:2181
      connect-string: centos700:2181,centos701:2181,centos702:2181



